version: '3.9'
name: 'booker'

services:
  auth:
    build: ./services/auth
    restart: unless-stopped
    ports:
      - "8080:8080"
    links:
      - users-postgres
  backend:
    build: ./services/backend
    restart: unless-stopped
    ports:
      - "8081:8080"
    links:
      - users-postgres
  tg_bot:
    build: ./services/tg_bot
    restart: unless-stopped
    ports:
      - "8082:8080"
    links:
      - users-postgres
  users-postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 256128
      POSTGRES_USER: postgres
      POSTGRES_DB: users
    ports:
      - "5433:5432"
    expose:
      - 5432
    volumes:
      - "users-postgres:/data/db"

volumes:
  users-postgres:
