version: '3.9'
name: 'booker'

services:
  auth:
    build: ./services/auth
    restart: unless-stopped
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: users-postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
    ports:
      - "8080:8080"
    links:
      - users-postgres
  backend:
    build: ./services/backend
    restart: unless-stopped
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: users-postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
    ports:
      - "8081:8080"
    links:
      - users-postgres
  users-postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    expose:
      - 5432
    volumes:
      - "users-postgres:/data/db"

volumes:
  users-postgres:
