# grafana/provisioning/datasources/prometheus.yml
apiVersion: 1

datasources:
  - name: DS_PROMETHEUS   # Имя источника данных в Grafana
    type: prometheus
    uid: booker_prometheus_ds
    url: http://prometheus:9090  # URL для доступа к Prometheus из Grafana (используем имя сервиса)
    access: proxy      # Доступ через Grafana бэкенд
    isDefault: true    # Сделать этот источник данных по умолчанию
    editable: true     # Разрешить редактирование в UI Grafana